node{
    def app
    stage('Clone repository'){

          checkout scm
}
    environment {
     DOCKERHUB_credentials=credentials('dockerhub')
     WORKSPACE='${WORKSPACE}/database2'

 }

    stage('Build image'){
      app = docker.build("database2", "./dockerfiles/database")
  }
    stage('Login'){
        
          sh 'docker login -u stefanzaharia93 -p 2c5f6afe-b64a-4a7a-bd99-58f0c92a7781'

    }
    stage('Pushing to dockerhub'){
          sh 'docker push stefanzaharia93/database2:latest'
      }
    }
pipeline{
   agent any
   stages{
      stage('Deploy'){
         steps{
            sshagent(credentials:['environment-server']){
               sh 'ssh -o StrictHostKeyChecking=no env@192.168.56.11 docker pull stefanzaharia93/database2:latest'
               sh 'scp -r ./dockerfiles/database/docker-compose.yml env@192.168.56.11:/home/env/'
               sh 'ssh -o StrictHostKeyChecking=no env@192.168.56.11 docker compose -f /home/env/docker-compose.yml up -d'
          }
        echo "Success deploy"
         }
       }
   }
}

