Vagrant.configure("2") do |config|

  os = "centos/8"
  net = "192.168.56"
  config.vm.define :deploy do |deploy_config|
      deploy_config.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = 4
          vb.name = "cicd"
      end
      deploy_config.vm.host_name = 'deploy'
      deploy_config.vm.box = "#{os}"
      deploy_config.vm.network "private_network", ip: "#{net}.10"
      deploy_config.vm.network "public_network"
      deploy_config.vm.provision "shell", inline: <<-SHELL
      cd /etc/yum.repos.d/
      sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
      sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      sudo yum update -y
      sudo yum install -y epel-release
      sudo yum -y update
      sudo yum install -y net-tools
      sudo yum install -y wget
      sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
      sudo rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
      sudo yum install jenkins --nogpgcheck
      sudo yum install -y java-1.8.0-openjdk.x86_64
      sudo yum install git
      sudo yum install
      sudo yum config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      sudo yum install docker-ce --nobest -y
      sudo systemctl start jenkins.service
      sudo systemctl enable jenkins.service

      SHELL
  end
  config.vm.define :environment do |environment_config|
      environment_config.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = 2
          vb.name = "env"
      end
      environment_config.vm.host_name = 'environment-server'
      environment_config.vm.box = "#{os}"
      environment_config.vm.network "private_network", ip: "#{net}.11"
      environment_config.vm.network "public_network"
      environment_config.vm.provision "shell", inline: <<-SHELL
      cd /etc/yum.repos.d/
      sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
      sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      sudo yum update -y
      sudo yum config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      sudo yum install docker-ce --nobest -y
      sudo yum update -y

      SHELL
  end
end
