pipeline{
   agent any
   stages{
      stage('Login server'){
         steps{
            sshagent(credentials:['environment_server']){
               sh 'ssh root@192.168.56.11'
          }
        echo "Success login"
         }
       }
   }
}
node{
    def app
    stage('Clone repository'){

          checkout scm
}
    environment {
     DOCKERHUB_credentials=credentials('dockerhub')
     WORKSPACE='${WORKSPACE}/load_balancer'

 }

    stage('Build image'){
      app = docker.build("load_balancer", "./dockerfiles/load_balancer")
  }
    stage('login'){
        
          sh 'docker login -u stefanzaharia93 -p 2c5f6afe-b64a-4a7a-bd99-58f0c92a7781'

    }
    stage('Pushing to dockerhub'){
          sh 'docker push stefanzaharia93/load_balancer:latest'
      }

}
