node{
    def app
    stage('Clone repository'){

          checkout scm
}
    environment {
     DOCKERHUB_credentials=credentials('dockerhub')
     WORKSPACE='${WORKSPACE}/application2'

 }

    stage('Build image'){
      app = docker.build("application2", "./dockerfiles/application")
  }
    stage('Login'){
        
          sh 'docker login -u stefanzaharia93 -p 2c5f6afe-b64a-4a7a-bd99-58f0c92a7781'

    }
    stage('Pushing to dockerhub'){
          sh 'docker push stefanzaharia93/application2:latest'
      }
    }
  pipeline{
   agent any
   stages{
      stage('Deploy'){
         steps{
            sshagent(credentials:['environment-server']){
               sh 'ssh -o StrictHostKeyChecking=no env@192.168.56.11'
               sh 'docker pull tefanzaharia93/application2:latest'
          }
        echo "Success deploy"
         }
       }
   }
}

